src/Entity/History.php
<?php

namespace App\Entity;

use App\Repository\HistoryRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=HistoryRepository::class)
 */
class History
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $score;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $date;

    /**
     * @ORM\Column(type="string", length=1000)
     */
    private $token;

    /**
     * @ORM\Column(type="integer")
     */
    private $categorie_id;

    /**
     * @ORM\OneToMany(targetEntity=Categorie::class, mappedBy="history")
     */
    private $categ_id;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $history_id;

    public function __construct()
    {
        $this->categ_id = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getScore(): ?int
    {
        return $this->score;
    }

    public function setScore(int $score): self
    {
        $this->score = $score;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(?\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getToken(): ?string
    {
        return $this->token;
    }

    public function setToken(string $token): self
    {
        $this->token = $token;

        return $this;
    }

    public function getCategorieId(): ?int
    {
        return $this->categorie_id;
    }

    public function setCategorieId(int $categorie_id): self
    {
        $this->categorie_id = $categorie_id;

        return $this;
    }

    /**
     * @return Collection|categorie[]
     */
    public function getCategId(): Collection
    {
        return $this->categ_id;
    }

    public function addCategId(categorie $categId): self
    {
        if (!$this->categ_id->contains($categId)) {
            $this->categ_id[] = $categId;
            $categId->setHistory($this);
        }

        return $this;
    }

    public function removeCategId(categorie $categId): self
    {
        if ($this->categ_id->removeElement($categId)) {
            // set the owning side to null (unless already changed)
            if ($categId->getHistory() === $this) {
                $categId->setHistory(null);
            }
        }

        return $this;
    }

    public function getHistoryId(): ?int
    {
        return $this->history_id;
    }

    public function setHistoryId(?int $history_id): self
    {
        $this->history_id = $history_id;

        return $this;
    }
}

src/Controller/ResultController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class ResultController extends AbstractController
{
    public function index(): Response
    {
        return $this->render('result/index.html.twig', [
            'score' => 'ResultController',
        ]);
    }
}

templates/result/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello ResultController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1><em><small class="text-muted">Resultat & Historique !</small></em></h1>
{%if score|length > 0%}
{%for scores in score%}
<div class="card text-white bg-primary mb-3" style="max-width: 20rem;">
  <div class="card-header">{{scores.date | date('y')}}</div>
  <div class="card-body">
    <h4 class="card-title">{{scores.score}}</h4>
    <p class="card-text">categorie (id pour l'instant): {{scores.categorieId}}</p>
  </div>
</div>
{%endfor%}
{%else%}
... Aucun historique ! 😱
{%endif%}

{% endblock %}